import swaggerJSDoc from 'swagger-jsdoc';
import swaggerUi from 'swagger-ui-express';
import { Application } from 'express';

const options: swaggerJSDoc.Options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Swift Food API',
      version: '1.0.0',
      description: 'API documentation generated by Swagger',
    },
    servers: [
      {
        url: 'http://localhost:3000/api', // update your server URL & port
      },
    ],
  },
  apis: ['./src/routers/*.ts'], // path to your route files with Swagger comments
};

const swaggerSpec = swaggerJSDoc(options);

export const setupSwagger = (app: Application) => {
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
};
